package com.thepokecraftmod.pokecraft.fabric.datagen.resources;

import com.thepokecraftmod.pokecraft.level.block.PokeCraftBlocks;
import com.thepokecraftmod.pokecraft.level.item.PokeCraftItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.models.BlockModelGenerators;
import net.minecraft.data.models.ItemModelGenerators;
import net.minecraft.data.models.model.ModelTemplates;
import net.minecraft.data.models.model.TexturedModel;

public class BlockItemModels extends FabricModelProvider {

    public BlockItemModels(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators generator) {
        generator.createTrivialBlock(PokeCraftBlocks.GREGANACL, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.ORANGE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.ORANGE_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.ORANGE_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.YELLOW_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.YELLOW_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.YELLOW_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.LIME_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.LIME_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.LIME_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.LIME_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.LIME_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.GREEN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.GREEN_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.GREEN_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.LIGHT_BLUE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.LIGHT_BLUE_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.LIGHT_BLUE_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.CYAN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CYAN_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CYAN_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.BLUE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.BLUE_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.BLUE_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.MAGENTA_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.MAGENTA_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.MAGENTA_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.PURPLE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.PURPLE_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.PURPLE_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.PINK_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.PINK_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.PINK_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.PINK_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.PINK_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.WHITE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.WHITE_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.WHITE_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.LIGHT_GRAY_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.LIGHT_GRAY_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.LIGHT_GRAY_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.GRAY_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.GRAY_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.GRAY_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.BLACK_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.BLACK_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.BLACK_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_CRACKED_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.BROWN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.BROWN_CUT_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.BROWN_CHISELED_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_SMOOTH_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_CRACKED_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.RED_CRACKED_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_SAND);
        generator.createTrivialCube(PokeCraftBlocks.LIME_SAND);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_SAND);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_SAND);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_SAND);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.PINK_SAND);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_SAND);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_SAND);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_SAND);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_SAND);
    }

    @Override
    public void generateItemModels(ItemModelGenerators generator) {
        generator.generateFlatItem(PokeCraftItems.BEAST_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHERISH_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DIVE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DREAM_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DUSK_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAST_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FRIEND_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GREAT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ANCIENT_GREAT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAL_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAVY_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEADEN_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEVEL_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LOVE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LURE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUXURY_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MASTER_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MOON_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NEST_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NET_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ORIGIN_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PARK_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POKE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ANCIENT_POKE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PREMIER_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUICK_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REPEAT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAFARI_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPORT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STRANGE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TIMER_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ULTRA_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ANCIENT_ULTRA_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WING_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ANTIDOTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AWAKENING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BERRY_JUICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BIG_MALASADA, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BURN_HEAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CASTELIACONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELIXIR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ENERGY_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ENERGY_ROOT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ETHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FRESH_WATER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FULL_HEAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FULL_RESTORE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAL_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HYPER_POTION, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_HEAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LAVA_COOKIE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEMONADE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUMIOSE_GALETTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_ELIXIR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_ETHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_HONEY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_POTION, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_REVIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MOOMOO_MILK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.OLD_GATEAU, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PARALYZE_HEAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POTION, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAGE_CANDY_BAR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REVIVAL_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REVIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SACRED_ASH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHALOUR_SABLE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SODA_POP, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SUPER_POTION, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SWEET_HEART, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AGUAV_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.APICOT_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ASPEAR_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BABIRI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BELUE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLUK_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHARTI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHERI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHESTO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHILAN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHOPLE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.COBA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.COLBUR_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CORNN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CUSTAP_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DURIN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ENIGMA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGY_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GANLON_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GREPA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HABAN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HONDEW_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IAPAPA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.JABOCA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KASIB_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KEBIA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KEE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KELPSY_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LANSAT_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEPPA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIECHI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUM_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGOST_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MARANGA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MICLE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NANAB_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NOMEL_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.OCCA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ORAN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PAMTRE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PASSHO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PAYAPA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PECHA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PERSIM_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PETAYA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PINAP_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POMEG_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUALOT_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RABUTA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAWST_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAZZ_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RINDO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROSELI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROWAP_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SALAC_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHUCA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SITRUS_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPELON_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STARF_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TAMATO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TANGA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WACAN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATMEL_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WEPEAR_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WIKI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.YACHE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ABILITY_SHIELD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ABSORB_BULB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AIR_BALLOON, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AMULET_COIN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ASSAULT_VEST, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BIG_ROOT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BINDING_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACK_BELT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACK_GLASSES, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACK_SLUDGE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLUNDER_POLICY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BOOSTER_ENERGY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BRIGHT_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CELL_BATTERY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHARCOAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHOICE_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHOICE_SCARF, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHOICE_SPECS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLEANSE_TAG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLEAR_AMULET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.COVERT_CLOAK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DAMP_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DESTINY_KNOT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_FANG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EJECT_BUTTON, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EJECT_PACK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EVERSTONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EVIOLITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_SHARE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXPERT_BELT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLAME_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLOAT_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FOCUS_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FOCUS_SASH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BUG_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARK_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIC_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAIRY_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGHTING_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIRE_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLYING_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GHOST_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASS_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GROUND_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NORMAL_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISON_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIC_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCK_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEEL_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATER_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRIP_CLAW, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HARD_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAT_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAVY_DUTY_BOOTS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICY_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FULL_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LAX_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUCK_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ODD_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PURE_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCK_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROSE_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SEA_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WAVE_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IRON_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LAGGING_TAIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEEK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEFTOVERS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIFE_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIGHT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIGHT_CLAY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LOADED_DICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUCKY_EGG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUCKY_PUNCH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUMINOUS_MOSS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MACHO_BRACE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGNET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MENTAL_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.METAL_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.METRONOME, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MIRACLE_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MIRROR_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MUSCLE_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MYSTIC_WATER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NEVER_MELT_ICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLANK_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRACO_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DREAD_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EARTH_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIST_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLAME_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICICLE_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.INSECT_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IRON_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MEADOW_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MIND_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PIXIE_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SKY_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPLASH_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPOOKY_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STONE_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TOXIC_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ZAP_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISON_BARB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_ANKLET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_BELT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_BRACER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_LENS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_WEIGHT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PROTECTIVE_PADS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PUNCHING_GLOVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUICK_CLAW, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUICK_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RED_CARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RING_TARGET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCKY_HELMET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROOM_SERVICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAFETY_GOGGLES, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCOPE_LENS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIC_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASSY_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MISTY_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIC_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHARP_BEAK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHED_SHELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHELL_BELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SILK_SCARF, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SILVER_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SMOKE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SMOOTH_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SNOWBALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SOFT_SAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SOOTHE_BELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPELL_TAG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STICKY_BARB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TERRAIN_EXTENDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.THICK_CLUB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.THROAT_SPRAY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TOXIC_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TWISTED_SPOON, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.UTILITY_UMBRELLA, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WEAKNESS_POLICY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WHITE_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WIDE_LENS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WISE_GLASSES, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ZOOM_LENS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ADAMANT_CRYSTAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ADAMANT_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AZURE_FLUTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLUE_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLEAR_BELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARK_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DNA_SPLICERS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BURN_DRIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHILL_DRIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DOUSE_DRIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHOCK_DRIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ENIGMA_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRACIDEA, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRISEOUS_CORE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRISEOUS_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GS_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICEROOT_CARROT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEGEND_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIGHT_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUNAR_WING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUSTROUS_GLOBE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUSTROUS_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BUG_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARK_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIC_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAIRY_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGHTING_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIRE_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLYING_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GHOST_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASS_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GROUND_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISON_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIC_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCK_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEEL_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATER_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.METEORITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MOON_FLUTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MYSTERIOUS_BALM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PRISON_BOTTLE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAINBOW_WING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RED_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REINS_OF_UNITY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REVEAL_GLASS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUSTED_SHIELD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUSTED_SWORD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCARLET_BOOK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCROLL_OF_DARKNESS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCROLL_OF_WATERS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHADEROOT_CARROT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SOUL_DEW, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPACE_BALM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPARKLING_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SUN_FLUTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TIDAL_BELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TIME_BALM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.VIOLET_BOOK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGMA_STONE, ModelTemplates.FLAT_ITEM);
    }
}
