/*
 * Copyright (C) 2023 ThePokeCraftMod
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package com.thepokecraftmod.pokecraft.fabric.datagen.resources;

import com.thepokecraftmod.pokecraft.PokeCraft;
import com.thepokecraftmod.pokecraft.level.block.PokeCraftBlocks;
import com.thepokecraftmod.pokecraft.level.item.PokeCraftItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.BlockFamilies;
import net.minecraft.data.BlockFamily;
import net.minecraft.data.models.BlockModelGenerators;
import net.minecraft.data.models.BlockModelGenerators.BlockFamilyProvider;
import net.minecraft.data.models.ItemModelGenerators;
import net.minecraft.data.models.model.ModelTemplates;
import net.minecraft.data.models.model.TextureMapping;
import net.minecraft.data.models.model.TexturedModel;
import net.minecraft.world.level.block.Blocks;

public class BlockItemModels extends FabricModelProvider {

    public BlockItemModels(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators generator) {
        generator.createTrivialBlock(PokeCraftBlocks.ORANGE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
            //generator.family(PokeCraftBlocks.ORANGE_SANDSTONE).stairs(PokeCraftBlocks.ORANGE_SANDSTONE_STAIRS).slab(PokeCraftBlocks.ORANGE_SANDSTONE_SLAB).wall(PokeCraftBlocks.ORANGE_SANDSTONE_WALL);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_ORANGE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_ORANGE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_ORANGE_SANDSTONE);
            //generator.family(PokeCraftBlocks.SMOOTH_ORANGE_SANDSTONE).stairs(PokeCraftBlocks.SMOOTH_ORANGE_SANDSTONE_STAIRS).slab(PokeCraftBlocks.SMOOTH_ORANGE_SANDSTONE_SLAB).wall(PokeCraftBlocks.SMOOTH_ORANGE_SANDSTONE_WALL);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_ORANGE_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.YELLOW_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_YELLOW_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_YELLOW_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_YELLOW_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_YELLOW_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.LIME_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_LIME_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_LIME_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_LIME_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_LIME_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.GREEN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_GREEN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_GREEN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_GREEN_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_GREEN_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.LIGHT_BLUE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_LIGHT_BLUE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_LIGHT_BLUE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_LIGHT_BLUE_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_LIGHT_BLUE_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.CYAN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_CYAN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_CYAN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_CYAN_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_CYAN_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.BLUE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_BLUE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_BLUE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_BLUE_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_BLUE_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.MAGENTA_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_MAGENTA_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_MAGENTA_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_MAGENTA_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_MAGENTA_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.PURPLE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_PURPLE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_PURPLE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_PURPLE_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_PURPLE_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.PINK_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_PINK_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_PINK_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_PINK_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_PINK_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.WHITE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_WHITE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_WHITE_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_WHITE_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_WHITE_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.LIGHT_GRAY_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_LIGHT_GRAY_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_LIGHT_GRAY_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_LIGHT_GRAY_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_LIGHT_GRAY_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.GRAY_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_GRAY_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_GRAY_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_GRAY_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_GRAY_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.BLACK_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_BLACK_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_BLACK_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_BLACK_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_BLACK_SANDSTONE);
        generator.createTrivialBlock(PokeCraftBlocks.BROWN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CUT_BROWN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialBlock(PokeCraftBlocks.CHISELED_BROWN_SANDSTONE, TexturedModel.CUBE_TOP_BOTTOM);
        generator.createTrivialCube(PokeCraftBlocks.SMOOTH_BROWN_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_BROWN_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_RED_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CRACKED_SANDSTONE);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_SAND);
        generator.createTrivialCube(PokeCraftBlocks.LIME_SAND);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_SAND);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_SAND);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_SAND);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.PINK_SAND);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_SAND);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_SAND);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_SAND);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_SAND);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_SAND);
        generator.createTrivialCube(PokeCraftBlocks.RUBY_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_RUBY_ORE);
        generator.createTrivialCube(PokeCraftBlocks.SAPPHIRE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_SAPPHIRE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.SAPPHIRE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.RUBY_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.CHARGESTONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.CHARGESTONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.CHARGESTONE_CRYSTAL);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_CHARGESTONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.RED_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.RED_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.LIME_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.LIME_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.PINK_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.PINK_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_PRISMARINE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_DARK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.RED_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.LIME_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.PINK_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_BRICKS);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_BRICKS);
        generator.createFurnace(PokeCraftBlocks.DEEPSLATE_FURNACE, TexturedModel.ORIENTABLE_ONLY_TOP);
        generator.createFurnace(PokeCraftBlocks.BLACKSTONE_FURNACE, TexturedModel.ORIENTABLE_ONLY_TOP);
        generator.createCraftingTableLike(PokeCraftBlocks.BIRCH_CRAFTING_TABLE, Blocks.BIRCH_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.SPRUCE_CRAFTING_TABLE, Blocks.SPRUCE_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.JUNGLE_CRAFTING_TABLE, Blocks.JUNGLE_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.ACACIA_CRAFTING_TABLE, Blocks.ACACIA_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.DARK_OAK_CRAFTING_TABLE, Blocks.DARK_OAK_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.MANGROVE_CRAFTING_TABLE, Blocks.MANGROVE_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.CHERRY_CRAFTING_TABLE, Blocks.CHERRY_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.BAMBOO_CRAFTING_TABLE, Blocks.BAMBOO_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.CRIMSON_CRAFTING_TABLE, Blocks.CRIMSON_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.WARPED_CRAFTING_TABLE, Blocks.WARPED_PLANKS, TextureMapping::craftingTable);
        generator.createCraftingTableLike(PokeCraftBlocks.DREAD_CRAFTING_TABLE, PokeCraftBlocks.DREAD_PLANKS, TextureMapping::craftingTable);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.RED_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.LIME_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.PINK_SHINGLES);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.RED_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.LIME_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.PINK_LIGHT);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.RED_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.LIME_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.PINK_GLOWSTONE);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.RED_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.LIME_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.PINK_REDSTONE_LAMP);
        generator.createTrivialCube(PokeCraftBlocks.WHITE_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_GRAY_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.GRAY_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.BLACK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.BROWN_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.RED_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.ORANGE_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.YELLOW_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.LIME_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.GREEN_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.CYAN_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.LIGHT_BLUE_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.BLUE_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.PURPLE_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.MAGENTA_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.PINK_PRISMARINE);
        generator.createTrivialCube(PokeCraftBlocks.FOSSIL_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_FOSSIL_ORE);
        generator.createTrivialCube(PokeCraftBlocks.Z_CRYSTAL_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_Z_CRYSTAL_ORE);
        generator.createTrivialBlock(PokeCraftBlocks.ORIGIN_DEBRIS, TexturedModel.COLUMN);
        generator.createTrivialCube(PokeCraftBlocks.FIRE_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_FIRE_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.FIRE_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.WATER_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_WATER_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.WATER_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.THUNDER_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_THUNDER_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.THUNDER_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.LEAF_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_LEAF_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.LEAF_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.MOON_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_MOON_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.MOON_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.SUN_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_SUN_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.SUN_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.SHINY_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_SHINY_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.SHINY_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.DUSK_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_DUSK_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DUSK_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.DAWN_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_DAWN_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DAWN_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.ICE_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_ICE_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.ICE_STONE_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.OVAL_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.DEEPSLATE_OVAL_STONE_ORE);
        generator.createTrivialCube(PokeCraftBlocks.OVAL_STONE_BLOCK);
        // Dread Blocks
        generator.woodProvider(PokeCraftBlocks.DREAD_LOG).logWithHorizontal(PokeCraftBlocks.DREAD_LOG).wood(PokeCraftBlocks.DREAD_WOOD);
        generator.woodProvider(PokeCraftBlocks.STRIPPED_DREAD_LOG).logWithHorizontal(PokeCraftBlocks.STRIPPED_DREAD_LOG).wood(PokeCraftBlocks.STRIPPED_DREAD_WOOD);
        generator.createTrivialCube(PokeCraftBlocks.DREAD_PLANKS);
            //generator.family(PokeCraftBlocks.DREAD_PLANKS).button(PokeCraftBlocks.DREAD_BUTTON).fence(PokeCraftBlocks.DREAD_FENCE).fenceGate(PokeCraftBlocks.DREAD_FENCE_GATE).pressurePlate(PokeCraftBlocks.DREAD_PRESSURE_PLATE).slab(PokeCraftBlocks.DREAD_SLAB).stairs(PokeCraftBlocks.DREAD_STAIRS);
        generator.createTrivialCube(PokeCraftBlocks.DREAD_LEAVES);
       // generator.createHangingSign(PokeCraftBlocks.STRIPPED_DREAD_LOG, PokeCraftBlocks.DREAD_HANGING_SIGN, PokeCraftBlocks.DREAD_WALL_HANGING_SIGN);
           // generator.createSimpleFlatItemModel(PokeCraftBlocks.DREAD_HANGING_SIGN);
        generator.createCrossBlockWithDefaultItem(PokeCraftBlocks.DREAD_SAPLING, BlockModelGenerators.TintState.NOT_TINTED);
        generator.createCrossBlockWithDefaultItem(PokeCraftBlocks.SHORT_GRASS, BlockModelGenerators.TintState.TINTED);
        // Natural
        generator.createTrivialCube(PokeCraftBlocks.WET_PACKED_MUD);
        generator.createTrivialCube(PokeCraftBlocks.PINK_AMETHYST_BLOCK);
        generator.createTrivialCube(PokeCraftBlocks.BUDDING_PINK_AMETHYST);
        generator.createAmethystCluster(PokeCraftBlocks.SMALL_PINK_AMETHYST_BUD);
        generator.createSimpleFlatItemModel(PokeCraftBlocks.SMALL_PINK_AMETHYST_BUD);
        generator.createAmethystCluster(PokeCraftBlocks.MEDIUM_PINK_AMETHYST_BUD);
        generator.createSimpleFlatItemModel(PokeCraftBlocks.MEDIUM_PINK_AMETHYST_BUD);
        generator.createAmethystCluster(PokeCraftBlocks.LARGE_PINK_AMETHYST_BUD);
        generator.createSimpleFlatItemModel(PokeCraftBlocks.LARGE_PINK_AMETHYST_BUD);
        generator.createAmethystCluster(PokeCraftBlocks.PINK_AMETHYST_CLUSTER);
            generator.createSimpleFlatItemModel(PokeCraftBlocks.PINK_AMETHYST_CLUSTER);
        generator.createTrivialCube(PokeCraftBlocks.SILK_BLOCK);
        generator.createCrossBlockWithDefaultItem(PokeCraftBlocks.WEB_STRING, BlockModelGenerators.TintState.NOT_TINTED);
        generator.createCrossBlockWithDefaultItem(PokeCraftBlocks.FRAYED_WEB_STRING, BlockModelGenerators.TintState.NOT_TINTED);
        generator.createCrossBlockWithDefaultItem(PokeCraftBlocks.SMALL_COBWEB, BlockModelGenerators.TintState.NOT_TINTED);

        generator.blockStateOutput.accept(BlockModelGenerators.createSimpleBlock(PokeCraftBlocks.BERRY_BUSH, PokeCraft.id("block/berry_bush_stage3")));
    }

    @Override
    public void generateItemModels(ItemModelGenerators generator) {
        // Minecraft
        generator.generateFlatItem(PokeCraftItems.EMERALD_BOOTS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_LEGGINGS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_CHESTPLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_HELMET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_BOOTS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_LEGGINGS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_CHESTPLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_HELMET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_BOOTS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_LEGGINGS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_CHESTPLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_HELMET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.DEEPSLATE_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.DEEPSLATE_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.DEEPSLATE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.DEEPSLATE_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.DEEPSLATE_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACKSTONE_SWORD, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACKSTONE_PICKAXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACKSTONE_AXE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACKSTONE_SHOVEL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACKSTONE_HOE, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.DIGGER_HANDLE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STONE_DRILL_BIT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IRON_DRILL_BIT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DIAMOND_DRILL_BIT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_DRILL_BIT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_DRILL_BIT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_DRILL_BIT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NETHERITE_DRILL_BIT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STONE_DIGGER_DRILL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.IRON_DIGGER_DRILL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.EMERALD_DIGGER_DRILL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY_DIGGER_DRILL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE_DIGGER_DRILL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.DIAMOND_DIGGER_DRILL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.NETHERITE_DIGGER_DRILL, ModelTemplates.FLAT_HANDHELD_ITEM);
        generator.generateFlatItem(PokeCraftItems.ULTRA_RECON_HELMET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ULTRA_RECON_CHESTPLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ULTRA_RECON_LEGGINGS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ULTRA_RECON_BOOTS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PINK_AMETHYST_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PINK_DIAMOND, ModelTemplates.FLAT_ITEM);



        // PokeBalls
        generator.generateFlatItem(PokeCraftItems.BEAST_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHERISH_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DIVE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DREAM_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DUSK_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAST_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FRIEND_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GREAT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ANCIENT_GREAT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAL_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAVY_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEADEN_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEVEL_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LOVE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LURE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUXURY_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MASTER_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MOON_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NEST_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NET_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ORIGIN_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PARK_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POKE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ANCIENT_POKE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PREMIER_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUICK_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REPEAT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAFARI_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPORT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STRANGE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TIMER_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ULTRA_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ANCIENT_ULTRA_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WING_BALL, ModelTemplates.FLAT_ITEM);
        // Restoration
        generator.generateFlatItem(PokeCraftItems.ANTIDOTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AWAKENING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BERRY_JUICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BIG_MALASADA, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BURN_HEAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CASTELIACONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELIXIR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ENERGY_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ENERGY_ROOT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ETHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FRESH_WATER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FULL_HEAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FULL_RESTORE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAL_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HYPER_POTION, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_HEAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LAVA_COOKIE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEMONADE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUMIOSE_GALETTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_ELIXIR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_ETHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_HONEY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_POTION, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_REVIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MOOMOO_MILK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.OLD_GATEAU, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PARALYZE_HEAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POTION, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAGE_CANDY_BAR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REVIVAL_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REVIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SACRED_ASH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHALOUR_SABLE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SODA_POP, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SUPER_POTION, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SWEET_HEART, ModelTemplates.FLAT_ITEM);
        // Berries
        generator.generateFlatItem(PokeCraftItems.AGUAV_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.APICOT_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ASPEAR_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BABIRI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BELUE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLUK_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHARTI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHERI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHESTO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHILAN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHOPLE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.COBA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.COLBUR_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CORNN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CUSTAP_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DURIN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ENIGMA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGY_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GANLON_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GREPA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HABAN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HONDEW_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IAPAPA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.JABOCA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KASIB_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KEBIA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KEE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KELPSY_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LANSAT_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEPPA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIECHI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUM_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGOST_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MARANGA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MICLE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NANAB_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NOMEL_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.OCCA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ORAN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PAMTRE_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PASSHO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PAYAPA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PECHA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PERSIM_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PETAYA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PINAP_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POMEG_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUALOT_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RABUTA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAWST_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAZZ_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RINDO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROSELI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROWAP_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SALAC_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHUCA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SITRUS_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPELON_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STARF_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TAMATO_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TANGA_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WACAN_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATMEL_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WEPEAR_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WIKI_BERRY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.YACHE_BERRY, ModelTemplates.FLAT_ITEM);
        // Held Items
        generator.generateFlatItem(PokeCraftItems.ABILITY_SHIELD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ABSORB_BULB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AIR_BALLOON, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AMULET_COIN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ASSAULT_VEST, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BIG_ROOT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BINDING_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACK_BELT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACK_GLASSES, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACK_SLUDGE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLUNDER_POLICY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BOOSTER_ENERGY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BRIGHT_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CELL_BATTERY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHARCOAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHOICE_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHOICE_SCARF, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHOICE_SPECS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLEANSE_TAG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLEAR_AMULET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.COVERT_CLOAK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DAMP_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DESTINY_KNOT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_FANG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EJECT_BUTTON, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EJECT_PACK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EVERSTONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EVIOLITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_SHARE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXPERT_BELT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLAME_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLOAT_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FOCUS_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FOCUS_SASH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BUG_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARK_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIC_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAIRY_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGHTING_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIRE_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLYING_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GHOST_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASS_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GROUND_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NORMAL_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISON_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIC_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCK_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEEL_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATER_GEM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRIP_CLAW, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HARD_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAT_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEAVY_DUTY_BOOTS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICY_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FULL_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LAX_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUCK_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ODD_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PURE_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCK_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROSE_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SEA_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WAVE_INCENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IRON_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LAGGING_TAIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEEK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEFTOVERS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIFE_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIGHT_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIGHT_CLAY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LOADED_DICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUCKY_EGG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUCKY_PUNCH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUMINOUS_MOSS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MACHO_BRACE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGNET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MENTAL_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.METAL_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.METRONOME, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MIRACLE_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MIRROR_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MUSCLE_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MYSTIC_WATER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NEVER_MELT_ICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLANK_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRACO_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DREAD_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EARTH_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIST_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLAME_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICICLE_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.INSECT_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IRON_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MEADOW_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MIND_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PIXIE_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SKY_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPLASH_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPOOKY_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STONE_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TOXIC_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ZAP_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISON_BARB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_ANKLET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_BELT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_BRACER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_LENS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POWER_WEIGHT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PROTECTIVE_PADS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PUNCHING_GLOVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUICK_CLAW, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUICK_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RED_CARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RING_TARGET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCKY_HELMET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROOM_SERVICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAFETY_GOGGLES, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCOPE_LENS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIC_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASSY_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MISTY_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIC_SEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHARP_BEAK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHED_SHELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHELL_BELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SILK_SCARF, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SILVER_POWDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SMOKE_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SMOOTH_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SNOWBALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SOFT_SAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SOOTHE_BELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPELL_TAG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STICKY_BARB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TERRAIN_EXTENDER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.THICK_CLUB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.THROAT_SPRAY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TOXIC_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TWISTED_SPOON, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.UTILITY_UMBRELLA, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WEAKNESS_POLICY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WHITE_HERB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WIDE_LENS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WISE_GLASSES, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ZOOM_LENS, ModelTemplates.FLAT_ITEM);
        // Legend Items
        generator.generateFlatItem(PokeCraftItems.RED_CHAIN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ADAMANT_CRYSTAL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ADAMANT_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AZURE_FLUTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLUE_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLEAR_BELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARK_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DNA_SPLICERS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BURN_DRIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHILL_DRIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DOUSE_DRIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHOCK_DRIVE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ENIGMA_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRACIDEA, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRISEOUS_CORE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRISEOUS_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GS_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICEROOT_CARROT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEGEND_PLATE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LIGHT_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUNAR_WING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUSTROUS_GLOBE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUSTROUS_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BUG_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARK_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIC_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAIRY_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGHTING_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIRE_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLYING_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GHOST_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASS_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GROUND_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISON_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIC_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCK_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEEL_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATER_MEMORY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.METEORITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MOON_FLUTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MYSTERIOUS_BALM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PRISON_BOTTLE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAINBOW_WING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RED_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REINS_OF_UNITY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REVEAL_GLASS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUSTED_SHIELD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUSTED_SWORD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCARLET_BOOK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCROLL_OF_DARKNESS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCROLL_OF_WATERS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHADEROOT_CARROT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SOUL_DEW, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPACE_BALM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPARKLING_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SUN_FLUTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TIDAL_BELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TIME_BALM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.VIOLET_BOOK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGMA_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SILVER_WING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.N_LUNARIZER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.N_SOLARIZER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CARROT_SEEDS, ModelTemplates.FLAT_ITEM);
        // Gimmick Items
        generator.generateFlatItem(PokeCraftItems.ALORAICHIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BUGINIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARKINIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DECIDIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGONIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EEVIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAIRIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGHTINIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIRIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLYINIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GHOSTIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASSIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GROUNDIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.INCINIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KOMMONIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUNALIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LYCANIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MARSHADIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MEWNIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MIMIKIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NORMALIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PIKANIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PIKASHUNIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISONIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PRIMARIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCKIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SNORLIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SOLGANIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEELIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TAPUNIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ULTRANECROZIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATERIUM_Z, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BUG_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARK_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIC_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAIRY_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGHTING_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIRE_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLYING_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GHOST_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASS_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GROUND_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NORMAL_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISON_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIC_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCK_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEEL_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATER_TERA_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ABOMASITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ABSOLITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AERODACTYLITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AGGRONITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ALAKAZITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ALTARIANITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AMPHAROSITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.AUDINITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BANETTITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BEEDRILLITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLASTOISINITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLAZIKENITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CAMERUPTITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHARIZARDITE_X, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHARIZARDITE_Y, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DIANCITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GALLADITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GARCHOMPITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GARDEVOIRITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GENGARITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GLALITITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GYARADOSITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HERACRONITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HOUNDOOMINITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KANGASKHANITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LATIASITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LATIOSITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LOPUNNITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LUCARIONITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MANECTITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAWILITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MEDICHAMITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.METAGROSSITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MEWTWONITE_X, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MEWTWONITE_Y, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PIDGEOTITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PINSIRITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SABLENITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SALAMENCITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCEPTILITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCIZORITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHARPEDONITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SLOWBRONITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEELIXITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SWAMPERTITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TYRANITARITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.VENUSAURITE, ModelTemplates.FLAT_ITEM);
        // Evolution
        generator.generateFlatItem(PokeCraftItems.AUSPICIOUS_ARMOR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLACK_AUGURITE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DAWN_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DEEP_SEA_SCALE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DEEP_SEA_TOOTH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_SCALE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DUBIOUS_DISC, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DUSK_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTIRIZER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIRE_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GALARICA_WREATH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GALARICA_CUFF, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.KINGS_ROCK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEAF_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LINKING_CORD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAGMARIZER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MALICIOUS_ARMOR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.METAL_COAT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MOON_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.OVAL_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHIPPED_POT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CRACKED_POT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PRISM_SCALE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PROTECTOR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAZOR_CLAW, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAZOR_FANG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REAPER_CLOTH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SACHET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHINY_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SUN_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BERRY_SWEET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLOVER_SWEET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLOWER_SWEET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LOVE_SWEET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RIBBON_SWEET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STAR_SWEET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STRAWBERRY_SWEET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SWEET_APPLE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TART_APPLE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.THUNDER_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.UPGRADE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATER_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WHIPPED_DREAM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PEAT_BLOCK, ModelTemplates.FLAT_ITEM);
        // Battle/Stat
        generator.generateFlatItem(PokeCraftItems.ABILITY_CAPSULE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ABILITY_PATCH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ADRENALINE_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BOTTLE_CAP, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CALCIUM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CARBOS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DIRE_HIT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DYNAMAX_CANDY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_CANDY_L, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_CANDY_M, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_CANDY_S, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_CANDY_XL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_CANDY_XS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLEVER_FEATHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GENIUS_FEATHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEALTH_FEATHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MUSCLE_FEATHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RESIST_FEATHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SWIFT_FEATHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLUFFY_TAIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GOLD_BOTTLE_CAP, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GUARD_SPEC, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HP_UP, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IRON, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ADAMANT_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BOLD_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BRAVE_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CALM_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CAREFUL_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GENTLE_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HASTY_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.IMPISH_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.JOLLY_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LAX_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LONELY_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MILD_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MODEST_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NAIVE_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NAUGHTY_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.QUIET_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RASH_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RELAXED_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SASSY_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SERIOUS_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TIMID_MINT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POKE_DOLL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PP_MAX, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PP_UP, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PROTEIN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RARE_CANDY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.X_ACCURACY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.X_ATTACK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.X_DEFENSE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.X_SP_ATK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.X_SP_DEF, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.X_SPEED, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ZINC, ModelTemplates.FLAT_ITEM);
        // Natural
        generator.generateFlatItem(PokeCraftItems.BLACK_APRICORN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLUE_APRICORN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GREEN_APRICORN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PINK_APRICORN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RED_APRICORN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WHITE_APRICORN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.YELLOW_APRICORN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BALM_MUSHROOM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BEACH_GLASS, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BIG_BAMBOO_SHOOT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BIG_MUSHROOM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BIG_NUGGET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BIG_PEARL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHALKY_STONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.COMET_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ARMOR_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CLAW_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.COVER_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DOME_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HELIX_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.JAW_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PLUME_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROOT_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAIL_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SKULL_FOSSIL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FOSSILIZED_BIRD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FOSSILIZED_DINO, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FOSSILIZED_DRAKE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FOSSILIZED_FISH, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GALARICA_TWIG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GOLD_LEAF, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HEART_SCALE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HONEY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LEAF_LETTER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LONE_EARING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MARBLE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PINK_NECTAR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PURPLE_NECTAR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RED_NECTAR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.YELLOW_NECTAR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NUGGET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.OLD_AMBER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ORIGIN_ORE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PEARL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PEARL_STRING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POLISHED_MUD_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PRETTY_FEATHER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BLUE_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GREEN_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RED_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.YELLOW_SHARD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SILVER_LEAF, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SMALL_BOUQUET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STAR_PIECE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STARDUST, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STRETCHY_SPRING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TINY_BAMBOO_SHOOT, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TINY_MUSHROOM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TROPICAL_SHELL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WISHING_CHIP, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WISHING_PIECE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WISHING_STAR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RARE_BONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RELIC_COPPER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RELIC_SILVER, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RELIC_GOLD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RELIC_VASE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RELIC_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RELIC_STATUE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RELIC_CROWN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STRANGE_SOUVENIR, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SAPPHIRE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RUBY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.CHARGESTONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ORIGIN_NUGGET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RAW_Z_ORE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.Z_CRYSTAL, ModelTemplates.FLAT_ITEM);
        // Player
        generator.generateFlatItem(PokeCraftItems.BALL_OF_MUD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ESCAPE_ROPE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ETERNAL_ICE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_ALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.LURE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_LURE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SUPER_LURE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POKE_TOY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.REPEL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MAX_REPEL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SUPER_REPEL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROTOM_CATALOG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SCATTER_BANG, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SEED_OF_MASTERY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SMOKE_BOMB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SNOW_BALL, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SPOILED_APRICORN, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEALTH_SPRAY, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STICKY_GLOB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BUG_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DARK_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DRAGON_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ELECTRIC_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FAIRY_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIGHTING_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FIRE_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.FLYING_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GHOST_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GRASS_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GROUND_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ICE_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.NORMAL_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.POISON_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.PSYCHIC_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ROCK_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.STEEL_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.WATER_TM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.HOPO_BERRY, ModelTemplates.FLAT_ITEM);
        // Key
        generator.generateFlatItem(PokeCraftItems.CATCHING_CHARM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.DYNAMAX_BAND, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EON_FLUTE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.EXP_CHARM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MARK_CHARM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.MEGA_BRACELET, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ODD_KEYSTONE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.OVAL_CHARM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.BOX_LINK, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.GOOD_ROD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.OLD_ROD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SUPER_ROD, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.SHINY_CHARM, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.TERA_ORB, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.Z_RING, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.ZYGARDE_CUBE, ModelTemplates.FLAT_ITEM);
        generator.generateFlatItem(PokeCraftItems.RIDE_PAGER, ModelTemplates.FLAT_ITEM);
    }
}
